language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
git:
  depth: 1
  submodules: false
branches:
  only:
  - master
install:
  - composer install --ignore-platform-reqs
script: php vendor/bin/simple-phpunit
