image: php:7.1.20

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip zip curl python-pip
          - pip install -r requirements.txt --upgrade --user
          - export PATH=~/.local/bin:$PATH
          - ls -al /root/.local/bin
          - /root/.local/bin/eb --help --debug --verbose
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - zip -r project.zip bin/ config/ public/ src/ templates/ vendor/ composer.json composer.lock composer.phar .ebextensions/ .elasticbeanstalk/
          - eb deploy --staged