controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /v1

app.swagger_ui:
    path: /v1/docs
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
